#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_

#define ZCL_CUSTOM_ATTRID_SWITCH_TYPE       0xF000
#define ZCL_CUSTOM_ATTRID_DEVICE_MODEL      0xF002



#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
